name: build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
      - 'README*'
  workflow_dispatch:
  
  
env:
  NFCTOOLSGUI_COMPILER: "Github Action"

jobs:
  build:
    if: ${{ always() }}
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest, macOS(ARM64) ]
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: install dependencies(macOS)
      if: runner.os == 'macOS'
      run: brew install autoconf automake libtool pkg-config
      
    - name: install dependencies(ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get install liblzma-dev libreadline-dev
        
    - name: Compile core files(Unix)
      if: runner.os != 'Windows'
      run: sh ./compile.sh
    
    - if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
    - name: Compile core files(Windows)
      if: runner.os == 'Windows'
      run: C:\msys64\msys2_shell.cmd -mingw64 -defterm -here -no-start -c ./compile.sh

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Compile GUI
      run: npm run make
      
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: NFCToolsGUI-${{ runner.os }}-${{ runner.arch }}
        path: "out/make/zip/*/*/*.zip"
